### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by kojix2**
I don't think the documentation is primitive.
There are too few developers, despite the fact that this is an important project used all over the world. 
Given this, the documentation is not the best, but it is good enough. It's not primitive at all.

### CODE REVIEW

**Comment by orlando-labs** [comment]
I fact, it's at maximum mediocre comparing to something people used to see in the Python world. I admit, the project is vital, and ruby needs scientific applications as a language. So I think there's a need to search for contributors somehow, not to mask the lack of good docs.

**Comment by kojix2** [comment]
So how do you think we can gather contributors?

**Comment by orlando-labs** [comment]
Near nowhere, I assume, until it's a sponsored project :( But it's still not a reason to remove a note about the obvious need for documentation quality bump.

**Comment by kojix2** [comment]
The criterion is whether or not we are doing a good job within the scope of sustainability.
It is not a comparison with Python or larger projects.

**Comment by orlando-labs** [comment]
There's no way to avoid comparison as the world of programming offers tons of tools and opportunities. And, looking around, Numo is somewhat sustainable, and I, personally, use it and value it in a vast row of projects. I'm paying respect to its authors and contributors. But I find it's docs poor (again, comparing to something the documentation should look and feel like in 2020).

**Comment by orlando-labs** [comment]
@kojix2, I got your point, but I have to say that wave of newcomers brings that small part of contributors at last. I'd really wanted to help easing the usage of Numo for developers with some shiny interactive example-rich docs, but currently I have no free resources after main projects and within one's power contributions to torch and torchaudio ruby ports.

**Comment by kojix2** [comment]
Enough time has passed that this pull request will be dropped.

**Pull request closed without merging**
