### PR TITLE
new method: NArray#fortran_contiguous?

### PR DESCRIPTION
**Pull request by naitoh**
I wrote new method "NArray#transpose?" for improve the performance of the a.dot(b.transpose).
(See #95 for details.)

### CODE REVIEW

**Comment by sonots** [comment]
It looks that the name is not proper because `a.transpose.transpose?` sometimes return false.
Maybe, f_contiguous?

**Comment by sonots** [comment]
You may refer cumo codes https://github.com/sonots/cumo/blob/master/ext/cumo/narray/gen/tmpl/gemm.c#L117-L180, and its tests https://github.com/sonots/cumo/blob/master/test/narray_test.rb#L335-L428.

**Comment by naitoh** [comment]
@sonots Thank you for pointing out.
I changed the method name to "f_contiguous?".

**Comment by masa16** [comment]
What about similar interface to [numpy.ascontiguousarray](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ascontiguousarray.html) ?

**Comment by sonots** [comment]
`ascontiguousarray` is one making and returning c-contiguous array.
`asfortranarray` makes and returns f-contiguous array.
They are not one to check c or f contiguity.
In NumPy, we can check with a.flags[‘C_CONTIGUOUS’] or a.flags[‘F_CONTIGUOUS’], but I do not think we should follow these APIs.

**Comment by masa16** [comment]
Sorry for my mistake.

**Comment by masa16** [comment]
My first impression was "What is 'f' ?"

**Comment by sonots** [comment]
I have getten started numerical computing from NumPy, so c-contiguous or f-contiguous were natural for me. But, are they not popular in common?

Raw major (c-contiguous) or column major (f-contiguous) might be another words to choose.
cuBLAS reference uses the word https://docs.nvidia.com/cuda/cublas/index.html.

**Comment by naitoh** [comment]
> My first impression was "What is 'f' ?"

The old NArray was "Fortran order".
Is "f" inappropriate?

https://www.slideshare.net/masa16tanaka/narray-and-scientific-computing-with-ruby/31

Or, is it better to implement it in C, rather than handling dot() operations by adding ruby methods?

**Comment by masa16** [comment]
The letter 'f' represents too many things and it is not obvious to represent 'Fortran'.
`fortran_contiguous` will be OK.

**Comment by naitoh** [comment]
@masa16  Thank you for pointing out.
I changed the method name to "fortran_contiguous?".

**Comment by naitoh** [comment]
Thanks!

**Pull request merged**
