### PR TITLE
Add static to functions that not necessary to be exported

### PR DESCRIPTION
**Pull request by sonots**
and remove unused functions.

This is a kind of **feedbacks** from Cumo to Numo.

# Background

I am currently creating CUDA-aware version of Numo, https://github.com/sonots/cumo.
I want to support conversion from Numo::NArray into Cumo::NArray.

To do it, I needed to support `require "numo/narray.so"` anyway.
I needed to resolve C symbol collisions between Numo and Cumo.

# What this PR does

While working to resolve symbol conflictions, I noticed that some functions are not used from outside of its file. So, I put `static` for them. I also found that some C functions are even not used from anywhere. So, I removed them.

# See also

https://github.com/sonots/cumo/pull/48

### CODE REVIEW

**Comment by sonots** [comment]
travis failed, but it looks not related with this PR.

**Comment by Try2Code** [comment]
do you plan to join numo and cumo?

**Comment by sonots** [comment]
Not considered yet.

**Comment by sonots** [comment]
Do you mean to merge Cumo with Numo? Not considered yet.

**Comment by Try2Code** [comment]
i though about having a single narray frontend and keeping cpu and gpu backend as a two possible implementations.

**Comment by sonots** [comment]
I think it is almost equivalent with merging Cumo into Numo.
Anyway, it is off-topic from this PR. I can tell you about Cumo more at twitter (@sonots) or slack (sciruby.slack.com, maybe).

**Comment by Try2Code** [comment]
but i usually work in HPC, where ppl decide at compile time, for which platform they create the executables.
thats why the specific soucecode for each implementation can be separated from the user code.
with precompiled libraries used in interpreted langs users have to decide at runtime, which implementation should be used. two separate libs might make more sense in that context

**Comment by sonots** [comment]
Currently, they are two seperated libs.

This PR is just to add `static` for functions which are not necessary to be exported (used only internally).

If they are exported intentionally, it is fine that this PR is closed.

**Comment by Try2Code** [comment]
thx for your thoughts, sry for messing things up here a little bit

**Pull request merged**
